// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoTRr9g02MSm2XdYI2p1cickVVBZNEgr8',
    appId: '1:511296083475:web:1a2c00addfc305dd2511e6',
    messagingSenderId: '511296083475',
    projectId: 'univibe-b4492',
    authDomain: 'univibe-b4492.firebaseapp.com',
    storageBucket: 'univibe-b4492.firebasestorage.app',
    measurementId: 'G-75H0ZZFYFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLEMPemi8rRJCUTkKFV0Oe6pC5EYaUqoA',
    appId: '1:511296083475:android:1ed52a452105aa562511e6',
    messagingSenderId: '511296083475',
    projectId: 'univibe-b4492',
    storageBucket: 'univibe-b4492.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1R8owgXppdix4A6Ol3ufkEtyD7X4T2pA',
    appId: '1:511296083475:ios:f3a14e035e9e97132511e6',
    messagingSenderId: '511296083475',
    projectId: 'univibe-b4492',
    storageBucket: 'univibe-b4492.firebasestorage.app',
    iosBundleId: 'com.example.univibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1R8owgXppdix4A6Ol3ufkEtyD7X4T2pA',
    appId: '1:511296083475:ios:f3a14e035e9e97132511e6',
    messagingSenderId: '511296083475',
    projectId: 'univibe-b4492',
    storageBucket: 'univibe-b4492.firebasestorage.app',
    iosBundleId: 'com.example.univibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoTRr9g02MSm2XdYI2p1cickVVBZNEgr8',
    appId: '1:511296083475:web:0cfce2de2c9c2c392511e6',
    messagingSenderId: '511296083475',
    projectId: 'univibe-b4492',
    authDomain: 'univibe-b4492.firebaseapp.com',
    storageBucket: 'univibe-b4492.firebasestorage.app',
    measurementId: 'G-Q6751MV6K6',
  );
}
